debug: false

server:
  port: 9001
  context-path: /medicalApi

spring:
  application:
    name: medical-api
  datasource:
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.43.203:3306/medical_system?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 0
    pool:
      max-active: 256
      max-idle: 8
      max-wait: -1
      min-idle: 0
mybatis:
  mapper-locations: classpath:mybatis/*.xml
